### ISSUE TITLE
MINI12864 - Marlin 1.1 - BOARD_RAMPS_14_EFB

### ISSUE THREAD

**Issue by dvseliteus** [makerbase-mks/Marlin#1]
No matter what I try I cannot get my Makerbase MKS MINI12864 v1.0 work with the latest version of Marlin 1.1.x
What is the correct LCD configuration?

**Comment by amrithmmh** [comment]
did you try to reverse the connector ..ie cut off the notch and put it in opposite direction
mks 1.4 boards have that problem

**Comment by dvseliteus** [comment]
I had the wrong ramps version in the firmware. Thanks for the help!

**Comment by amrithmmh** [comment]
@dvseliteus i have a mks gen 1.4 and i tried the ramps marlin firmware but sometimes when i give commands like move +x axis 10mm 5 times it moves only 4 times
do you know anything about that? is mks boards unlreliable?

**Comment by mike-diff** [comment]
@amrithmmh what board do you have specified in Marlin?
Should be #define MOTHERBOARD BOARD_MKS_13

**Comment by amrithmmh** [comment]
@3daddict it turns out that one of my motor was dying and now gone for good
the mks board is ok and no i gave  #define MOTHERBOARD BOARD_RAMPS_14_EFB and now it works fine though
